# Bsed on : https://github.com/csinguva/NLP4SocialGood/blob/master/keywords.py
# Completed by P. Fortuna and L. Pérez

KEYWORDS = {
    "Agriculture": [
        "farming",
        "agriculture",
        "sustainable agriculture",
        "farmer",
        "vegetation",
        "livestock",
        "gardening",
        "irrigation",
        "domestication",
        "wheat",
        "usda",
        "soil",
        "agricultural",
        "artisanal",
        "factory farm",
        "rural"
    ],
    "Education": [
        "tutor",
        "pedagogy",
        "tuition",
        "textbook",
        "education",
        "educational",
        "diploma",
        "classroom",
        "vocational",
        "literacy",
        "mooc",
    ],
    "Environmental sustainability": [
        "invasive species",
        "poaching",
        "sustainability",
        "wildlife",
        "pollution",
        "biodiversity",
        "climate action",
        "oceans",
        "land degradation"
        "carbon",
        "wildfire",
        "disaster",
        "smart grid",
        "wind farm",
        "renewable",
        "endangered",
        "clean energy",
        "habitat",
        "atmospheric",
        "hybrid vehicle",
        "hurricane",
        "disaster",
        "clean water access",
    ],
    "Healthcare": [
        "healthcare",
        "well-being",
        "health",
        "disability",
        "mental",
        "vaccination",
        "disease",
        "infection",
        "assistive",
        "medical",
        "clinical",
        "HIV",
        "community health",
        "public health",
        "clinic",
        "physician",
        "nutrition",
        "x-ray",
        "medicare",
        "symptom",
        "epidemic",
        "opiode",
        "cancer",
        "nodules",
        "covid",
        "autism",
        "impairment",
        "impaired",
        "anorexia",
        "suicide ideation",
        "suicidal ideation",
        "depression",
        "attention deficit hyperactivity disorder",
        "ADHD",
        "stroke",
        "Huntington's disease",
        "dementia",
        "amyotrophic lateral sclerosis",
    ],
    "Media corrupted communication": [
        "false news",
        "fake news",
        "polarization",
        "politic",
        "newspaper",
        "journalism",
        "news article",
        "election",
        "trustworthy",
        "influence maximization",
        "abusive language",
        "toxicity",
        "offense",
        "hate speech",
        "aggressive",
        "aggression",
        "microaggression",
        "fact checking",
    ],
    "Public safety": [
        "crime",
        "police",
        "safety",
        "fraud",
        "terrorism",
        "peace",
        "war",
        "alert",
        "protect",
        "terrorist",
        "patrol",
        "surveillance",
        "crisis",
        "human trafficking",
        "harmful policing",
    ],
    "Social care": [
        "socially assisting robotics",
        "social aid",
        "homeless",
        "refugees",
        "charity",
        "poverty eradication",
        "welfare",
        "volunteer",
        "social worker",
        "socioeconomic",
        "food security",
        "starvation",
        "refugees",
        "gender gap",
        "gender equality",
        "racial",
        "racism",
        "racist",
        "sexism",
        "sexist",
        "ageing",
        "aged",
        "migrants",
        "immigrants",
        "social context",
        "social cost",
        "social justice",
        "international development",
        "low-resource",
        "low-resourced",
        "low resource",
        "low resourced",
        "Stereotypes",
    ],
    "Transportation": [
        "transportation",
        "traffic",
        "rideshare",
        "subway",
        "carpool",
        "passenger",
        "railroad",
        "travel",
        "mobility",
        "ride-sharing",
    ],
    "Urban planning": [
        "emergency",
        "cost of living",
        "low-income",
        "low income",
        "drug",
        "sanitation",
        "affordable energy",
        "home abandonment",
        "sustainable cities",
        "sustainable communities",
        "responsible comsumption",
        "responsible production",
        "gentrification",
    ],
    "Language Disorders": [
        "Anarthria",
        "Dysarthria",
        "dysglossia",
        "Agnosia",
        "asemia",
        "asymbolia",
        "Aphasia",
        "aphrasia",
        "Dysphasia",
        "schizophasia",
        "logorrhea",
        "Paraphasia",
        "Aprosodia",
        "Dysprosody",
        "Alogia",
        "Alexia",
        "Dyslexia",
        "Paralexia",
        "Agraphia",
        "Dysgraphia",
        "graphorrhea",
        "Paragraphia",
        "Alalia",
        "Dyslalia",
        "coprolalia",
        "echolalia",
        "glossolalia",
        "Palilalia",
        "Anomia",
        "Dysnomia",
        "Apraxia",
        "Dyspraxia",
        "Dysphemia",
        "Dysorthography",
        "Agrammatism",
        "Paragrammatism",
        "Aphonia",
        "Dysphonia",
    ],
    "Ethics": [
        "ethical",
        "ethic",
        "ethics",
        "bias",
        "biasses",
        "debiasing",
        "privacy",
        "dual use",
        "data statement",
        "data protection",
        "fairness",
        "trustable",
        "trustworthy",
        "equity",
    ],
    "Social good": [
        "interpretable",
        "interpretability",
        "explainable",
        "explainability",
        "accountability",
        "social good",
        "social impact",
        "social implications",
    ],
    "Systems of change and collaboration": [
        "grassroots",
        "NGO",
        "social entrepreneurs",
        "activists",
        "activist",
        "inclusive",
        "financial cost",
        "economic growth",
        "Sociotechnical Systems",
    ],

}

